:imagesdir: ./images
:icons: font
:toc: left

= Openshift S2I with CLI

Before we already learn how to deploy source to image using web console. However, same goal can be achieve also using openshift CLI

== Create Node.JS Application

=== Review The Source Code

Open git repository https://github.com/openshift/nodejs-ex.git to review the code what is build and deploy to openshift

=== Find Image Builder

To find the correct builder for python we can use below command:

-----
$ oc get is -n openshift
-----

We will get result similiar like below:

-----

NAME                                  DOCKER REPO                                                         TAGS                            UPDATED
dotnet                                172.30.245.248:5000/openshift/dotnet                                1.0,1.1,2.0 + 1 more...         2 months ago
dotnet-runtime                        172.30.245.248:5000/openshift/dotnet-runtime                        2.0,latest                      2 months ago
fis-java-openshift                    registry.access.redhat.com/jboss-fuse-6/fis-java-openshift          latest,2.0,2.0-15 + 3 more...   2 months ago
fis-karaf-openshift                   registry.access.redhat.com/jboss-fuse-6/fis-karaf-openshift         2.0,2.0-15,latest + 3 more...   2 months ago
httpd                                 172.30.245.248:5000/openshift/httpd                                 2.4,latest                      2 months ago
jboss-amq-62                          172.30.245.248:5000/openshift/jboss-amq-62                          1.1,1.2,1.3 + 3 more...         5 months ago
jboss-amq-63                          172.30.245.248:5000/openshift/jboss-amq-63                          1.0,1.1,1.2                     5 months ago
jboss-datagrid65-client-openshift     172.30.245.248:5000/openshift/jboss-datagrid65-client-openshift     1.1,1.0                         5 months ago
jboss-datagrid65-openshift            172.30.245.248:5000/openshift/jboss-datagrid65-openshift            1.4,1.5,1.2 + 1 more...         5 months ago
jboss-datagrid71-client-openshift     172.30.245.248:5000/openshift/jboss-datagrid71-client-openshift     1.0                             5 months ago
jboss-datagrid71-openshift            172.30.245.248:5000/openshift/jboss-datagrid71-openshift            1.0,1.1                         5 months ago
jboss-datavirt63-driver-openshift     172.30.245.248:5000/openshift/jboss-datavirt63-driver-openshift     1.0,1.1                         5 months ago
jboss-datavirt63-openshift            172.30.245.248:5000/openshift/jboss-datavirt63-openshift            1.0,1.1,1.2 + 1 more...         5 months ago
jboss-decisionserver62-openshift      172.30.245.248:5000/openshift/jboss-decisionserver62-openshift      1.2                             5 months ago
jboss-decisionserver63-openshift      172.30.245.248:5000/openshift/jboss-decisionserver63-openshift      1.3,1.4                         5 months ago
jboss-decisionserver64-openshift      172.30.245.248:5000/openshift/jboss-decisionserver64-openshift      1.0,1.1                         5 months ago
jboss-eap64-openshift                 172.30.245.248:5000/openshift/jboss-eap64-openshift                 1.3,1.4,1.5 + 3 more...         2 months ago
jboss-eap70-openshift                 172.30.245.248:5000/openshift/jboss-eap70-openshift                 1.6,1.3,1.4 + 1 more...         2 months ago
jboss-eap71-openshift                 172.30.245.248:5000/openshift/jboss-eap71-openshift                 1.0-TP,TP                       5 months ago
jboss-processserver63-openshift       172.30.245.248:5000/openshift/jboss-processserver63-openshift       1.3,1.4                         5 months ago
jboss-processserver64-openshift       172.30.245.248:5000/openshift/jboss-processserver64-openshift       1.0,1.1                         5 months ago
jboss-webserver30-tomcat7-openshift   172.30.245.248:5000/openshift/jboss-webserver30-tomcat7-openshift   1.1,1.2,1.3                     5 months ago
jboss-webserver30-tomcat8-openshift   172.30.245.248:5000/openshift/jboss-webserver30-tomcat8-openshift   1.1,1.2,1.3                     5 months ago
jboss-webserver31-tomcat7-openshift   172.30.245.248:5000/openshift/jboss-webserver31-tomcat7-openshift   1.1,1.0                         2 months ago
jboss-webserver31-tomcat8-openshift   172.30.245.248:5000/openshift/jboss-webserver31-tomcat8-openshift   1.1,1.0                         2 months ago
jenkins                               172.30.245.248:5000/openshift/jenkins                               latest,v3.7,1 + 4 more...       2 weeks ago
mariadb                               172.30.245.248:5000/openshift/mariadb                               10.1,latest                     2 months ago
mongodb                               172.30.245.248:5000/openshift/mongodb                               2.6,3.2,latest + 1 more...      2 months ago
mysql                                 172.30.245.248:5000/openshift/mysql                                 latest,5.6,5.7 + 1 more...      2 months ago
nodejs                                172.30.245.248:5000/openshift/nodejs                                6,latest,4 + 1 more...          2 months ago
ose-recycler                          172.30.245.248:5000/openshift/ose-recycler                          v3.6,latest,v3.3 + 2 more...    5 months ago
perl                                  172.30.245.248:5000/openshift/perl                                  latest,5.20,5.24 + 1 more...    2 months ago
php                                   172.30.245.248:5000/openshift/php                                   7.0,latest,5.6 + 1 more...      2 months ago
postgresql                            172.30.245.248:5000/openshift/postgresql                            9.4,9.5,latest + 1 more...      2 months ago
python                                172.30.245.248:5000/openshift/python                                3.4,3.5,latest + 2 more...      2 months ago
redhat-openjdk18-openshift            172.30.245.248:5000/openshift/redhat-openjdk18-openshift            1.2,1.0,1.1                     2 months ago
redhat-sso70-openshift                172.30.245.248:5000/openshift/redhat-sso70-openshift                1.3,1.4                         5 months ago
redhat-sso71-openshift                172.30.245.248:5000/openshift/redhat-sso71-openshift                1.0,1.1,1.2                     5 months ago
redis                                 172.30.245.248:5000/openshift/redis                                 3.2,latest                      2 months ago
ruby                                  172.30.245.248:5000/openshift/ruby                                  2.2,2.3,2.4 + 2 more...         2 months ago
-----

We will have lot of builder that can be choosen. Moreover, for example we want to deploy python application we find there python builder with several version that can be choose. To descriibe more about the builder we can use below command:

----
$ oc describe is/nodejs -n openshift
----

and detail describtion for nodejs builder can be check here:

----
Name:			nodejs
Namespace:		openshift
Created:		7 days ago
Labels:			<none>
Annotations:		openshift.io/display-name=Node.js
			openshift.io/image.dockerRepositoryCheck=2018-07-22T16:27:01Z
Docker Pull Spec:	172.30.1.1:5000/openshift/nodejs
Image Lookup:		local=false
Unique Images:		4
Tags:			5

6
  tagged from registry.access.redhat.com/rhscl/nodejs-6-rhel7:latest

  Build and run Node.js 6 applications on RHEL 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-nodejs-container.
  Tags: builder, nodejs
  Supports: nodejs:6, nodejs
  Example Repo: https://github.com/openshift/nodejs-ex.git

  * registry.access.redhat.com/rhscl/nodejs-6-rhel7@sha256:c757f417bdb2548bbc24ccb30789f787e751f1c1ed73cd9cf3dff7acfcc39c94
      7 days ago

8 (latest)
  tagged from registry.access.redhat.com/rhscl/nodejs-8-rhel7:latest

  Build and run Node.js 8 applications on RHEL 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-nodejs-container.
  Tags: builder, nodejs
  Example Repo: https://github.com/openshift/nodejs-ex.git

  * registry.access.redhat.com/rhscl/nodejs-8-rhel7@sha256:7b26a9d8ace47e939a9fcdca61620dbe47d1b936e68983e252cca50991704c7c
      7 days ago


----

Another way for search like web console catalog is using below command:

-----
$ oc new-app --search python
Image streams (oc new-app --image-stream=<image-stream> [--code=<source>])
----
python
  Project: openshift
  Tags:    2.7, 3.4, 3.5, latest

Docker images (oc new-app --docker-image=<docker-image> [--code=<source>])
----
python
  Registry: Docker Hub
  Tags:     latest

-----

== Deploy nodejs Application

=== Deploy MongoDB database

----
$ oc new-app mongodb
----


=== Create Build and Deploy

To create build and deploy in same time we can use *oc new-app* command like below:

----
$ oc new-app openshift/nodejs:8~https://github.com/openshift/nodejs-ex.git --name=mynodejsapss
--> Found image 03fdd4e (3 months old) in image stream "openshift/python" under tag "3.5" for "openshift/python:3.5"

    Node.js 8 
    --------- 
    Node.js 8 available as container is a base platform for building and running various Node.js 8 applications and frameworks. Node.js is a platform built on Chrome's JavaScript runtime for easily building fast, scalable network applications. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient, perfect for data-intensive real-time applications that run across distributed devices.

    Tags: builder, nodejs, nodejs8

    * A source build using source code from https://github.com/openshift/nodejs-ex.git will be created
      * The resulting image will be pushed to image stream "mynodejsapss:latest"
      * Use 'start-build' to trigger a new build
    * This image will be deployed in deployment config "mynodejsapss"
    * Port 8080/tcp will be load balanced by service "mynodejsapss"
      * Other containers can access this service through the hostname "mynodejsapss"

--> Creating resources ...
    imagestream "mynodejsapss" created
    buildconfig "mynodejsapss" created
    deploymentconfig "mynodejsapss" created
    service "mynodejsapss" created
--> Success
    Build scheduled, use 'oc logs -f bc/mynodejsapss' to track its progress.
    Application is not exposed. You can expose services to the outside world by executing one or more of the commands below:
     'oc expose svc/mynodejsapss' 
    Run 'oc status' to view your app.
 
----

=== Check and Review the Application

We can check the status build and deployment here:

----
$ oc status
svc/mynodejsapss - 172.30.173.202:8080
  dc/mynodejsapss deploys istag/mynodejsapss:latest <-
    bc/mynodejsapss source builds https://github.com/openshift/nodejs-ex.git on openshift/nodejs:8 
      build #1 running for 18 hours - e79929f: Merge pull request #191 from adambkaplan/sclorg-rename (Honza Horak <hhorak@redhat.com>)
    deployment #1 waiting on image or update
----

We know that build is started and we can check the build log here:

----
$ oc logs bc/mynodejsapss
CCloning "https://github.com/openshift/nodejs-ex.git" ...
	Commit:	e79929f0b6f22038214879adfc242840d8c694b8 (Merge pull request #191 from adambkaplan/sclorg-rename)
	Author:	Honza Horak <hhorak@redhat.com>
	Date:	Tue Jul 24 18:24:51 2018 +0200
  ....
----

=== Create Route

Now the application is already deployed then we can try to expose the service through Route using command below:

----
$ oc expose service mypythonapps
route "mypythonapps" exposed

$ oc get route
NAME           HOST/PORT                                                    PATH      SERVICES       PORT       TERMINATION   WILDCARD
mypythonapps   mypythonapps-yohanes-demo.apps.rhpds.openshift.opentlc.com             mypythonapps   8080-tcp                 None

----

Now we can open route url above in browser  http://mypythonapps-yohanes-demo.apps.rhpds.openshift.opentlc.com

=== Add MongoDB Binding

Remember that you created a binding when you deployed the MongoDB database. You now add that binding to your newly created application to provide persistence.

. Click mynodejsapps under the Deployment header to open the deployment configuration for your Node.JS application.
. Click the Environment tab.
- This Node.JS application can receive the database configuration via environment variables. Unfortunately the variable names that the application expects are slightly different from the field names in your binding secret. If they were identical you could just bind the whole secret. But they are not, so you need to bind individual fields.
. Click the Add Value from Config Map or Secret link.
- his displays a row with a name field, a list of secret names, and a list of values associated with the secret.
. Create four environment variables (rows) as Below:

[options="header,footer"]
|========
|Name|Select a Resource	|Secret Key
|MONGODB_USER|Select your secret from the pull-down list.|username
|MONGODB_DATABASE | Select your secret from the pull-down list.|database_name
|MONGODB_PASSWORD|Select your secret from the pull-down list.|password
|MONGODB_ADMIN_PASSWORD|Select your secret from the pull-down list.|admin_password
|========

[start=5]
. Click Add Value to add a regular environment variable and use DATABASE_SERVICE_NAME as the Name and mongodb as the Value.
- This enables the example application that you use for this lab to construct the URI itself. Instead of passing the URI from the secret, you pass the service name for your database (mongodb).
. Click Save to update the deployment configuration with the new environment values.
. Click Overview in the left-hand panel to go back to the project overview.
. Observe that the number next to your deployment configuration (mynodejsapps) increased because you changed the configuration.
- Every time you change a configuration setting, OpenShift creates a new version of the deployment configuration and redeploys the application. This ensures that you can go back to a previous version if the change created a problem.
. To verify that your application bound successfully to the database, click the route to your application again.
- Expect to see a section at the bottom right corner, labeled DB Connection Info, with details about your database connection. You can also see that every time you refresh the page, the page view count increases by one.

You have just created a database service from the OpenShift service catalog. You picked an ephemeral service—meaning that it does not persist any data over pod restarts—which is fine for this demonstration.

You also created an application from Node.JS source code in a GitHub repository and bound the database to the application. This enabled the application to use the database without really knowing anything about the implementation details of the database. This database can be in the same project (as in this example), a different project, a different OpenShift cluster, somewhere outside OpenShift but still in your data center, or dynamically provisioned in the cloud. All that the application needs is the connection information and the rest is handled by OpenShift.