FROM registry.access.redhat.com/rhel7.5:latest
LABEL maintainer="Yohanes <ysono@redhat.com>" \
      description="My First Container"
RUN echo "my first command" && \
    echo "my second command"
CMD bash -c "while true; do echo test; sleep 5; done"
